# Generated by Django 4.2.1 on 2023-05-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffleapp', '0003_article_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollresult',
            old_name='user_id',
            new_name='user_count',
        ),
    ]
