# Generated by Django 4.2.1 on 2023-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffleapp', '0004_rename_user_id_pollresult_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='option',
            field=models.CharField(default='Poll option', max_length=200),
        ),
    ]
