# Generated by Django 4.2.1 on 2023-05-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffleapp', '0005_alter_polloption_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='option',
            field=models.CharField(default='Poll question', max_length=200),
        ),
    ]
