# Generated by Django 4.2.1 on 2023-05-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waffleapp', '0006_alter_polloption_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollresult',
            name='user_count',
        ),
        migrations.AddField(
            model_name='pollresult',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='waffleapp.article'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='waffleapp.poll'),
        ),
    ]
