# Generated by Django 4.2.1 on 2023-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffleapp', '0008_alter_pollresult_poll_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PollResult',
        ),
    ]
